swagger: "2.0"
info:
  description: Swagger file to go with our server
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

paths:
  /people:
    get:
      operationId: "api.people.read"
      tags:
        - "People"
      summary: "People data structure"
      description: "Reads list of people"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
